<a href="https://colab.research.google.com/github/gojiyashailesh/Data-Science/blob/main/1_Python_Coding_Ques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Convert string to int using single line of code

In [ ]:
a = "5"

In [ ]:
print(int(a))

5


### Convert a string to a list

In [ ]:
str1 = "Analytics Vidhya"

In [ ]:
print(str1.split(" "))

['Analytics', 'Vidhya']


### Reverse a string

In [ ]:
str1 = "Analytics Vidhya"

In [ ]:
str2 = ""
for i in str1:
    str2 = i + str2
print("The original string is: ", str1)
print("The reversed string is: ", str2)

The original string is:  Analytics Vidhya
The reversed string is:  ayhdiV scitylanA


### Sort a list in Python

In [ ]:
my_list = [3, 1, 2]

In [ ]:
my_list.sort()
print(my_list)

[1, 2, 3]


### Delete a file in Python

In [ ]:
f = open("txt1.txt", "x")

In [ ]:
import os

In [ ]:
os.remove("txt1.txt")

### Access element of a list

In [ ]:
my_list = [10, 20, 30, 40, 50]

In [ ]:
first_element = my_list[0]
print("First element:", first_element)  # Output: First element: 10

First element: 10


In [ ]:
third_element = my_list[2]
print("Third element:", third_element)  # Output: Third element: 30

Third element: 30


In [ ]:
last_element = my_list[-1]
print("Last element:", last_element)  # Output: Last element: 50

Last element: 50


### Delete element from a list

#### Method #1

In [ ]:
list1 = [1, 2, 3, 4]

In [ ]:
list1.remove(2)
print(list1)

[1, 3, 4]


#### Method #2

In [ ]:
list1.pop(1)
print(list1)

[1, 4]


### Delete an entire list

In [ ]:
list1 = [1, 2, 3, 4]

In [ ]:
list1.clear()

In [ ]:
list1

[]

### Reverse an array

#### Method #1

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3, 4])

In [ ]:
arr2 = np.flip(arr1)
print(arr2)

[4 3 2 1]


#### Method #2

In [ ]:
arr2 = arr1[::-1]
print(arr2)

[4 3 2 1]


### Access, delete, update element in Numpy Array

In [ ]:
arr1 = [1, 2, 3, 4]

In [ ]:
# To access element
print(arr1[0])

1


In [ ]:
# To delete element
x = np.delete(arr1, 0)
print(x)

[2 3 4]


In [ ]:
# To update element
arr1[1] = 100
print(arr1)

[1, 100, 3, 4]


### Concatenate two lists

In [ ]:
lst1 = ['W', 'a', 'w', 'b']
lst2 = ['e', 're', 'riting', 'log']

In [ ]:
lst3 = [x + y for x, y in zip(lst1, lst2)]

print(lst3)

['We', 'are', 'writing', 'blog']


### Square of list elements

#### Method #1

In [ ]:
# Define a sample list
my_list = [1, 2, 3, 4]

# Square each element using a for loop and list comprehension
squared_list = [x * x for x in my_list]

# Print the original and squared lists
print("Original list:", my_list)
print("Squared list:", squared_list)

Original list: [1, 2, 3, 4]
Squared list: [1, 4, 9, 16]


#### Method #2

In [ ]:
# Square each element using the map() function and a lambda expression
squared_list_map = list(map(lambda x: x * x, my_list))
# Convert to list for clarity

# Print the squared list (same output as method 1)
print("Squared list using map():", squared_list_map)

Squared list using map(): [1, 4, 9, 16]


### Difference b/w Split & Join

In [ ]:
a = 'This is a string'
b = a.split(' ')

print(b)

['This', 'is', 'a', 'string']


In [ ]:
c = "-".join(b)

print(c)

This-is-a-string
